### PR TITLE
Adding a "Main Action" option

### PR DESCRIPTION
**Pull request by jgodi**
Adding in a "Main Action" option to be added onto the `mfb-button`. 

I have a use-case for this because I would like my main button to be "Save" then on hover show a "Cancel" button. This solves the problem pretty easy.

### CODE REVIEW

**Comment by jgodi** [comment]
This is a potential solution to https://github.com/nobitagit/ng-material-floating-button/issues/6. I look at that fork and didn't want to add another dependency for something so simple.

**Comment by nobitagit** [comment]
Does this work for you? It doesn't for me, please share an example of how this is supposed to work.

**Comment by jgodi** [comment]
Updated the PR to reflect an example in the base demo, angular material demo and the README.md. Hope that helps!

**Comment by nobitagit** [comment]
Hi there, sorry for the late response on this.

I have pulled the changes and now it works for me. There's still one thing I don't get, though.
What's the difference between the proposed solution and putting an `ng-click` on the main button?

If in the demo provided I select `hover` and `fire` it does work ok (but why not using ng-click directly?).
If, instead, I select `click` and `fire` I would expect the handler not to fire the first time I click (the menu opens) and the fire the subsequent times I click. In the the demo the click handler always fires, disregarding the menu being open or closed. Again, sorry if I'm missing something and thanks for contributing.

**Comment by jgodi** [comment]
If you put a `ng-click` on the main button, then it goes on the `ul` tag and gets fired also when you click all the sub-buttons that you place in the menu.

**Pull request merged**
