### PR TITLE
Fixed a display bug occurring in Chrome

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
To reproduce open a sample page on chrome and scroll.
The UI won't update until you manually trigger a rerender.

Applying [this](http://stackoverflow.com/questions/17068361/chrome-positionfixed-inside-positionabsolute-breaking-with-iframe-video) fixed solved the problem.

### CODE REVIEW

**Comment by nobitagit** [comment]
I was actually surprised that I did get away without `backface-visibility` problems with this.
Anyway I tried reproduce this and could not see the issue, can you explain further and help me out with this?

That being said I will quite surely merge your PR, so it's just a matter of myself seeing this issue live. Thanks for the contribution.

**Comment by DanielMSchmidt** [comment]
I will provide one soon, thanks for merging. One bonus question: Why is the original project not in bower? This way it could be included here in the bower.json and the fix would have been done in the main project where it would belong.

**Comment by nobitagit** [comment]
I went for including it as a git submodule rather than a Bower dep as I was developing the css at the same time from both repos (mfb and ng-mfb) and submodules are the best way - at least for me - to have a two way data flow and keep everything is sync.

I could both pull changes from [mfb](https://github.com/nobitagit/material-floating-button) to here and push from here to the [mfb repo](https://github.com/nobitagit/material-floating-button), instead of changing the css in the upstream repo and pull from here every time I needed I tweak.
In that sense my suggestion in the readme to edit the CSS code in the original repo is just for practical reasons for me and to keep Issues here only related to Angular, but any code implemented here can be easily transferred from here to Mfb with a simple push.

Now that the code is much more stable it probably makes sense to move it out to Bower, though.

**Comment by DanielMSchmidt** [comment]
I had the same problem developing the PR (using my original project as base). I found [bower link](http://bower.io/docs/api/#link) was a really nice solution, behaves like you described the git submodules. just FYI ;)

**Comment by DanielMSchmidt** [comment]
I assume this PR can be closed?

**Comment by DanielMSchmidt** [comment]
Closed 1,5 years later due to inactivity

**Pull request closed without merging**
