### PR TITLE
Add possibility to style buttons with a class

### LINKED ISSUE #18: feat: button colors
With angular-material, it would be nice to set custom classes on the menu and buttons. So each button could be a different color.

### PR DESCRIPTION
**Pull request by cebor**
I added a new attribute `button-class` to set a custom class for the ngMaterial buttons.

I think this will fix #18

### CODE REVIEW

**Comment by cebor** [comment]
Ok, i see this isn't working like expected ...

**Comment by nobitagit** [comment]
Have you understood why it isn't working? Sorry I have little time these days.

**Comment by cebor** [comment]
Yes i think it has something to do, that the material directive changes the classes on compilation.

**Comment by nobitagit** [comment]
Ok, keep me posted on this one then

**Pull request closed without merging**
